### ISSUE TITLE
Relatinoship between SuSiE and SuSiEGLMM

### ISSUE THREAD

**Issue by JosephLalli** [cumc/SuSiEGLMM.jl#65]
Hi there,
I'm interested in using this implementation of SuSiE in my research pipeline, but I'm hesitant about using it if it's someone's side project. Is this project actively updated to keep up with SuSiE's implementation and bug fixes?

-Joe

**Comment by gaow** [comment]
@JosephLalli this is an experimental package and not meant for production now. I'll move it off the public radar to avoid confusions. We'll bring it back when ready. Thank you!
